// app/layout.jsx
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import StoreProvider from "./StoreProvider";
import ThemeProvider from "./ThemeProvider";
import MyMsalProvider from "../msal/MyMsalProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app"
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <StoreProvider>
            <ThemeProvider>
              <MyMsalProvider>
                <main>
                  <div className="w-full text-center">
                    <h1 className="text-3xl font-bold text-gray-700 mb-2">
                      You are logged in
                    </h1>
                  </div>
                  {children} {/* Render children inside main */}
                </main>
              </MyMsalProvider>
            </ThemeProvider>
          </StoreProvider>
        </Providers>
      </body>
    </html>
  );
}