export default function Rules() {

  return (
<div className="flex flex-col justify-start items-start px-4 overflow-auto h-full py-5">
      <div className="bg-secondary rounded-lg p-8 md:w-3/4 lg:w-2/4 text-primaryText">
        <h1 className="text-3xl font-bold text-start mb-6">Meal Master Rules and Policies</h1>
        
        <div className="space-y-4 text-start">
          <div>
            <h2 className="text-xl font-semibold">User Conduct</h2>
            <p className="mt-2">
              Users are expected to interact with the app respectfully and responsibly. 
              Any misuse of the platform, including submitting harmful or inappropriate content, will result in account suspension.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold">Content Ownership</h2>
            <p className="mt-2">
              All recipes generated by Meal Master are owned by the user who creates them. 
              However, by using the app, you grant Meal Master the right to use your generated recipes for promotional purposes.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold">Privacy Policy</h2>
            <p className="mt-2">
              Meal Master is committed to protecting your privacy. 
              We do not share your personal information with third parties without your consent. 
              For more details, please review our comprehensive Privacy Policy.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold">Account Security</h2>
            <p className="mt-2">
              You are responsible for maintaining the confidentiality of your account information, including your password. 
              Please notify us immediately if you suspect any unauthorized access to your account.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold">Recipe Accuracy</h2>
            <p className="mt-2">
              While Meal Master strives to provide accurate and reliable recipes, 
              we cannot guarantee the success of every recipe generated. 
              Users should use their discretion and culinary skills when following recipes.
            </p>
          </div>

          <div>
            <h2 className="text-xl font-semibold">Modifications to Policies</h2>
            <p className="mt-2">
              Meal Master reserves the right to modify these rules and policies at any time. 
              Users will be notified of any significant changes through the app or via email.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
